blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Quick RSS Official Website
    url: https://wangchujiang.com/paste-quick/
    about: Introduction to the Quick RSS app on the official website!